export const DEFAULT_SWIMLANE_BACKGROUND = '#FFFFFF';
export const DEFAULT_SWIMLANE_BORDER = '#58CCFC';
export const DEFAULT_NODE_BACKGROUND = '#C3E9F9';
export const DEFAULT_NODE_BORDER = '#707070';
