
import { UploadImageTool } from '@app/shared/texteditor/widgets/upload-image.tool';
import { InsertVideoTool } from '@app/shared/texteditor/widgets/insert-video.tool';

const RICH_TEXT_TOOLS = [
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'justifyLeft',
  'justifyCenter',
  'justifyRight',
  'justifyFull',
  'insertUnorderedList',
  'insertOrderedList',
  'insertUpperRomanList',
  'insertLowerRomanList',
  'indent',
  'outdent',
  'createLink',
  'unlink',
  'insertImage',
  UploadImageTool(),
  InsertVideoTool(),
  'insertFile',
  'subscript',
  'superscript',
  'tableWizard',
  'createTable',
  'addRowAbove',
  'addRowBelow',
  'addColumnLeft',
  'addColumnRight',
  'deleteRow',
  'deleteColumn',
  'mergeCellsHorizontally',
  'mergeCellsVertically',
  'splitCellHorizontally',
  'splitCellVertically',
  'tableAlignLeft',
  'tableAlignCenter',
  'tableAlignRight',
  'viewHtml',
  'formatting',
  'cleanFormatting',
  'copyFormat',
  'applyFormat',
  'fontName',
  'fontSize',
  'foreColor',
  'backColor',
];

const SIMPLE_TEXT_TOOLS = [
  'formatting',
  'fontName',
  'fontSize',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'foreColor',
  'backColor',
  'justifyLeft',
  'justifyCenter',
  'justifyRight',
  'justifyFull',
  'insertUnorderedList',
  'insertOrderedList',
  'insertUpperRomanList',
  'insertLowerRomanList',
  'indent',
  'outdent',
];

const BASIC_EXPANDING_TOOLS = [
  'bold',
  'italic',
  'underline',
  'insertUnorderedList',
  'insertOrderedList',
  'formatting',
  'createLink',
  'unlink',
  'insertImage',
  UploadImageTool(),
];

export const RICH_TEXT_EDITOR_TOOLS_CONFIG = {
  RICH_TEXT_TOOLS,
  SIMPLE_TEXT_TOOLS,
  BASIC_EXPANDING_TOOLS
}
